### ISSUE TITLE
Train errors on CUB

### ISSUE THREAD

**Issue by YuanXinCherry** [elias-ramzi/ROADMAP#4]
After configuring the runtime environment according to the guide, I ran the training code with the following `error：
`Traceback (most recent call last):
  File "roadmap/single_experiment_runner.py", line 7, in <module>
    import roadmap.run as run
  File "/code/yx/SIGIR/ROADMAP/roadmap/run.py", line 10, in <module>
    from ray import tune
  File "/home/yx/anaconda3/envs/osap/lib/python3.7/site-packages/ray/tune/__init__.py", line 2, in <module>
    from ray.tune.tune import run_experiments, run
  File "/home/yx/anaconda3/envs/osap/lib/python3.7/site-packages/ray/tune/tune.py", line 14, in <module>
    from ray.tune.utils.callback import create_default_callbacks
  File "/home/yx/anaconda3/envs/osap/lib/python3.7/site-packages/ray/tune/utils/callback.py", line 7, in <module>
    from ray.tune.progress_reporter import TrialProgressCallback
  File "/home/yx/anaconda3/envs/osap/lib/python3.7/site-packages/ray/tune/progress_reporter.py", line 28, in <module>
    raise ImportError("ray.tune in ray > 0.7.5 requires 'tabulate'. "
ImportError: ray.tune in ray > 0.7.5 requires 'tabulate'. Please re-run 'pip install ray[tune]' or 'pip install ray[rllib]'.
`

**Comment by elias-ramzi** [comment]
Hi,

It seems that you have a missing requirement (`ray[tune]`)
Could you try:
```
pip install ray[tune]
```
Hope that helps.

**Comment by YuanXinCherry** [comment]
I have tried and still get the same error

**Comment by YuanXinCherry** [comment]
what is the version of `ray`?

**Comment by elias-ramzi** [comment]
I have : `ray == 1.2.0`

**Comment by YuanXinCherry** [comment]
I tried to change the version of ray to 1.2.0, but I still get the same error.

I would like to ask if the requirements are as follows：
`numpy
torch==1.8.1
torchvision==0.9.1
faiss-gpu==1.6.5
pillow
pandas
tqdm
tensorboard
matplotlib
pytorch-metric-learning
timm
ray[tune]
ray[default]
hydra-core==1.0.6
hydra_colorlog==1.0.1
hydra-ax-sweeper==1.1.0
hydra-ray-launcher==0.1.4`

**Comment by elias-ramzi** [comment]
Yes those are the correct requirements.

Could you try pulling the latest version of the repository ? It should not be needing `ray` now for the examples scripts.

**Comment by YuanXinCherry** [comment]
Thank you very much!
I have tried  the latest version of the repository and the code can be trained and tested successfully.

**Comment by YuanXinCherry** [comment]
Excuse me, I would like to know the computational complexity of AP based loss compared in the paper as well as ROADMAP.

**Comment by elias-ramzi** [comment]
Do you mean the hardware requirements for the code ?

**Comment by YuanXinCherry** [comment]
I mean the computational complexity of the algorithm. For example, the computational complexity of FastAP is O((N+P)L), where P and N denote the number of positive and negative samples, and L denotes the number of bins.

**Comment by elias-ramzi** [comment]
Hi sorry for the delay.

- **SupAP** has a computational complexity of `O(P(N+P))`
- The **calibration loss** has a computational complexity of `O(B^2)`

Where P and N denote the number of positive and negative samples, and B denotes the batch size.

**Comment by YuanXinCherry** [comment]
Thank you very much for your patient reply! This work has inspired me greatly.

**Comment by elias-ramzi** [comment]
Glad to hear that :)
