### ISSUE TITLE
DG_{AP} in Eq. 8

### ISSUE THREAD

**Issue by MaroonAmor** [elias-ramzi/ROADMAP#7]
Is there any guarantee that DG_{AP} is non-negative?

For example, we have two batches:
- Batch 1: `red < red < green < green < green`
- Batch 2: `red < green < green < green < red`

The AP of Batch 1 is 1.0, and the AP of Batch 2 is 0.64. The average AP over such two batches is 0.82.

If these two batches form a dataset like this: `red < red < red < green < green < green < red < green < green < green`,
then the AP over the dataset is 0.915, and DG_{AP} here is -0.095, right?

Could you help me understand this part? Please let me know if I misunderstood something. Thanks. @elias-ramzi

**Comment by elias-ramzi** [comment]
Hi ! 
Sorry for the late response, I was not at work.

Thank you for your question.

You are right, DG_{AP} can be negative.

Note that in Eqs. 8 & 9 we assume that the AP per batch is 1, in this case DG_{AP} > 0. Indeed the mean AP per batch is 1 and the global AP has a maximum value of 1.

In your example, where this assumption is not correct, the SupAP loss would still optimize on batch 1 (as the AP loss on this batch is not 0).

I hope this will help you !

**Comment by MaroonAmor** [comment]
Hi @elias-ramzi, thanks a lot for your answer. It makes sense to me now. This assumption was not clear to me from the paper. I was confused at the beginning since it seems like the upper bound is proposed in a general setting.

Under the assumption that the AP per batch is 1, this upper bound should hold. Thanks again for your work.
