### ISSUE TITLE
XBM Setting -> Potential lead to out of memory

### ISSUE THREAD

**Issue by di0002ya** [elias-ramzi/ROADMAP#8]
Dear author,  

I notice that size (xbm setting) for sop dataset is set to dataset size. Will this setting result in out of memory?

**Comment by elias-ramzi** [comment]
Hi,

Storing all the item instances of SOP in a tensor on GPU is quite small, ie 60000x512 which is ~1.4GB.
The authors of XBM explain that this is why this method is memory effective. You only have to compute embeddings and gradients for small batches, as you would do in a typical setting.

Hope this helps :)

**Comment by di0002ya** [comment]
I see. Thanks for the explanation.
